version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
    container_name: elasticsearch
    restart: always
    environment:
      - cluster.name=labmeinc
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - path.repo=/snapshots
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g
    volumes:
      - ./elasticsearch/es_data:/usr/share/elasticsearch/data
      - ./elasticsearch/snapshots:/snapshots
    ports:
      - 9200:9200
    networks:
      - esnet
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.2
    container_name: kibana
    restart: always
    depends_on:
      - elasticsearch
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - esnet
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  logstash:
    image: hasecuritysolutions/logstash:v6.5.2
    container_name: logstash
    restart: always
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - pipeline.batch.size=125
      - config.reload.automatic=true
      - config.reload.interval=30s
      - queue.type=persisted
      - "LS_JAVA_OPTS:-Xmx2g -Xms1g"
    mem_limit: 4g
    ports:
      - 5044:5044
      - 5045:5045
      - 6050:6050
    volumes:
      - ./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./logstash/logstash_configs:/opt/logstash_configs:ro
      - ./logstash/translate:/opt/elastic_stack/logstash/translate:ro
      - ./logstash/rules:/etc/nsm/rules:ro
      - ./logstash/persistent_data:/usr/share/logstash/data
    networks:
      - esnet
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  freq_server:
    image: hasecuritysolutions/freq_server:v1.0
    container_name: freq_server
    restart: always
    ports:
      - 10004:10004
    networks:
      - esnet
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  domain_stats2:
    image: hasecuritysolutions/domain_stats2
    container_name: domain_stats2
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /opt/domain_stats2/data:/opt/domain_stats2/data
    networks:
      - esnet
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  cerebro:
    image: hasecuritysolutions/cerebro:v1.0
    container_name: cerebro
    depends_on:
      - elasticsearch
    ports:
      - 9000:9000
    networks:
      - esnet
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  elastalert:
    image: hasecuritysolutions/elastalert:v1.0
    container_name: elastalert
    restart: always
    depends_on:
      - elasticsearch
    volumes:
      - ./elastalert:/etc/elastalert:ro
    networks:
      - esnet
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  esnet:
    driver: bridge